### ISSUE TITLE
Gametrak movement not registering when left x (X1) is 0

### ISSUE THREAD

**Issue by achimkoh** [samparkewolfe/Sound_Control#1]
Hello! First of all, what an exciting project you have here. I just got a Gametrak controller to play around with Wekinator and I was happy to discover this app which seems much easier to use.

One thing I've noticed is that Sound Control doesn't seem to respond to Gametrak's movement when the left stick is tilted all the way left. In the screen capture below, you can see another max patch (in the background) sensing the movement while Sound Control doesn't. Thought I'd report it since it may be a bug.

![gametrak720](https://user-images.githubusercontent.com/3594463/39280435-6cf82da4-48cd-11e8-84d7-0a4e0bef5b79.gif)

Mac Sierra 10.12.6

**Comment by samparkewolfe** [comment]
Hey, thanks for finding this!

I have just recreated this bug on my machine and will get on fixing it asap.

**Comment by samparkewolfe** [comment]
I have fixed error and merged the fix into the master branch.

I have also made a new release of this app which includes the fix.
https://github.com/samparkewolfe/Sound_Control/releases/tag/v1.2
